apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-web-server
  namespace: tutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      containers:
      - name: app
        image: ecojuntak/go-web-server:v0.1