apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-rest-api
  namespace: tutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
      - name: app
        image: ecojuntak/go-rest-api:v0.0.1
